In [1]:
library('tidyverse')

Warning message:
“Failed to locate timezone database”
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
df.marathon = read.csv('../data//marathon.csv')
df.marathon |> head()

  year name                       country       time       race.time MF
1 2019 Lawrence Cherono           Kenya         2H 7M 57S  2.132500  Men's
2 2018 Yuki Kawauchi              Japan         2H 15M 58S 2.266111  Men's
3 2017 Geoffrey Kirui             Kenya         2H 9M 37S  2.160278  Men's
4 2016 Lemi Berhanu               Ethiopia      2H 12M 45S 2.212500  Men's
5 2015 Lelisa Desisa              Ethiopia      2H 9M 17S  2.154722  Men's
6 2014 Mebrahtom "Meb" Keflezighi United States 2H 8M 37S  2.143611  Men's
  country.simple
1 Kenya
2 Japan
3 Kenya
4 Ethiopia
5 Ethiopia
6 United States

Use `arrange` to find the best race time.

In [30]:
df.marathon |>
    arrange(race.time)

    year name                       country       time       race.time MF
1   2011 Geoffrey Mutai             Kenya         2H 3M 2S   2.050556  Men's
2   2010 Robert Kiprono Cheruiyot   Kenya         2H 5M 52S  2.097778  Men's
3   2006 Robert Kipkoech Cheruiyot  Kenya         2H 7M 14S  2.120556  Men's
4   1994 Cosmas Ndeti               Kenya         2H 7M 15S  2.120833  Men's
5   1998 Moses Tanui                Kenya         2H 7M 34S  2.126111  Men's
6   2008 Robert Kipkoech Cheruiyot  Kenya         2H 7M 46S  2.129444  Men's
7   1986 Robert de Castella         Australia     2H 7M 51S  2.130833  Men's
8   2019 Lawrence Cherono           Kenya         2H 7M 57S  2.132500  Men's
9   1992 Ibrahim Hussein            Kenya         2H 8M 14S  2.137222  Men's
10  1990 Gelindo Bordin             Italy         2H 8M 19S  2.138611  Men's
11  2014 Mebrahtom "Meb" Keflezighi United States 2H 8M 37S  2.143611  Men's
12  2009 Deriba Merga               Ethiopia      2H 8M 42S  2.145000  Men's
13  1988 Ibrahim Hussein            Kenya         2H 8M 43S  2.145278  Men's
14  1982 Alberto Salazar            United States 2H 8M 52S  2.147778  Men's
15  1983 Greg A. Meyer              United States 2H 9M 0S   2.150000  Men's
16  2002 Rodgers Rop                Kenya         2H 9M 2S   2.150556  Men's
17  1989 Abebe Mekonnen             Ethiopia      2H 9M 6S   2.151667  Men's
18  1996 Moses Tanui                Kenya         2H 9M 15S  2.154167  Men's
19  2015 Lelisa Desisa              Ethiopia      2H 9M 17S  2.154722  Men's
20  1995 Cosmas Ndeti               Kenya         2H 9M 22S  2.156111  Men's
21  1981 Toshihiko Seko             Japan         2H 9M 26S  2.157222  Men's
22  1979 Bill Rodgers               United States 2H 9M 27S  2.157500  Men's
23  1993 Cosmas Ndeti               Kenya         2H 9M 33S  2.159167  Men's
24  2017 Geoffrey Kirui             Kenya         2H 9M 37S  2.160278  Men's
25  2001 Lee Bong-Ju                South Korea   2H 9M 43S  2.161944  Men's
26  2000 Elijah Lagat               Kenya         2H 9M 47S  2.163056  Men's
27  1999 Joseph Chebet              Kenya         2H 9M 52S  2.164444  Men's
28  1975 Bill Rodgers               United States 2H 9M 55S  2.165278  Men's
29  2003 Robert Kipkoech Cheruiyot  Kenya         2H 10M 11S 2.169722  Men's
30  1978 Bill Rodgers               United States 2H 10M 13S 2.170278  Men's
⋮   ⋮    ⋮                          ⋮             ⋮          ⋮         ⋮
142 1929 John C. Miles              Canada        2H 33M 8S  2.552222  Men's
143 1937 Walter Young               Canada        2H 33M 20S 2.555556  Men's
144 1932 Paul de Bruyn              Germany       2H 33M 36S 2.560000  Men's
145 1936 Ellison M. Brown           United States 2H 33M 40S 2.561111  Men's
146 1985 Lisa Larsen-Weidenbach     United States 2H 34M 6S  2.568333  Women's
147 1980 Jacqueline Gareau          Canada        2H 34M 28S 2.574444  Women's
148 1930 Clarence H. DeMar          United States 2H 34M 48S 2.580000  Men's
149 1979 Joan Benoit                United States 2H 35M 15S 2.587500  Women's
150 1938 Leslie S. Pawson           United States 2H 35M 34S 2.592778  Men's
151 1928 Clarence H. DeMar          United States 2H 37M 7S  2.618611  Men's
152 1904 Michael Spring             United States 2H 38M 4S  2.634444  Men's
153 1905 Frederick Lorz             United States 2H 38M 25S 2.640278  Men's
154 1900 John P. Caffery            Canada        2H 39M 44S 2.662222  Men's
155 2018 Desiree Linden             United States 2H 39M 54S 2.665000  Women's
156 1927 Clarence H. DeMar          United States 2H 40M 22S 2.672778  Men's
157 1903 John C. Lorden             United States 2H 41M 29S 2.691389  Men's
158 1898 Ronald J. MacDonald        Canada        2H 42M 0S  2.700000  Men's
159 1975 Liane Winter               Germany       2H 42M 24S 2.706667  Women's
160 1902 Sammy A. Mellor            United States 2H 43M 12S 2.720000  Men's
161 1978 Gayle S. Barron            United States 2H 44M 52S 2.747778  Women's
162 1906 Timothy Ford               United States 2H 45M 45S 2.762500  Men's
163 1931 James P. Henigan           United States 2H 46M 45S 2.779167  Men's
164 1976 Kim Merritt                United States 2H 47M 10S 2.786111  Women's
165 1974 Michiko (Miki) Gorman      United States 2H 47M 11S 2.786389  Women's
166 1977 Michiko (Miki) Gorman      United States 2H 48M 33S 2.809167  Women's
167 1909 Henri Renaud               United States 2H 53M 36S 2.893333  Men's
168 1899 Lawrence Brignolia         United States 2H 54M 38S 2.910556  Men's
169 1897 John J. McDermott          United States 2H 55M 10S 2.919444  Men's
170 1973 Jacqueline A. Hansen       United States 3H 5M 59S  3.099722  Women's
171 1972 Nina Kuscsik               United States 3H 10M 26S 3.173889  Women's
    country.simple
1   Kenya
2   Kenya
3   Kenya
4   Kenya
5   Kenya
6   Kenya
7   other
8   Kenya
9   Kenya
10  other
11  United States
12  Ethiopia
13  Kenya
14  United States
15  United States
16  Kenya
17  Ethiopia
18  Kenya
19  Ethiopia
20  Kenya
21  Japan
22  United States
23  Kenya
24  Kenya
25  other
26  Kenya
27  Kenya
28  United States
29  Kenya
30  United States
⋮   ⋮
142 other
143 other
144 other
145 United States
146 United States
147 other
148 United States
149 United States
150 United States
151 United States
152 United States
153 United States
154 other
155 United States
156 United States
157 United States
158 other
159 other
160 United States
161 United States
162 United States
163 United States
164 United States
165 United States
166 United States
167 United States
168 United States
169 United States
170 United States
171 United States

What are the best race times by country?

In [20]:
df.marathon |>
    group_by(country) |>
    summarize(min_time = min(race.time))

   country           min_time
1  Australia         2.130833
2  Belgium           2.316111
3  Canada            2.246111
4  Colombia          2.312500
5  Comm. Ind. States 2.395278
6  England           2.175000
7  Ethiopia          2.145000
8  Finland           2.237222
9  Germany           2.362500
10 Greece            2.490833
11 Guatemala         2.531389
12 Ireland           2.227500
13 Italy             2.138611
14 Japan             2.157222
15 Kenya             2.050556
16 Korea             2.427500
17 New Zealand       2.262500
18 Norway            2.409167
19 Poland            2.405000
20 Portugal          2.408333
21 Russia            2.422222
22 South Korea       2.161944
23 Sweden            2.530556
24 United States     2.143611
25 Yugoslavia        2.431667

In what year was the difference between the men's and women's winning time smallest? Use this table:

In [21]:
df = df.marathon |>
    select(year, MF, race.time) |>
    tidyr::spread(MF, race.time) |>
    drop_na() |>
    rename(men = `Men's`, women = `Women's`)

df |> head()

  year men      women
1 1972 2.260833 3.173889
2 1973 2.267500 3.099722
3 1974 2.227500 2.786389
4 1975 2.165278 2.706667
5 1976 2.338611 2.786111
6 1977 2.246111 2.809167

In [28]:
mutate(df, difference = women - men)

   year men      women    difference
1  1972 2.260833 3.173889 0.9130556
2  1973 2.267500 3.099722 0.8322222
3  1974 2.227500 2.786389 0.5588889
4  1975 2.165278 2.706667 0.5413889
5  1976 2.338611 2.786111 0.4475000
6  1977 2.246111 2.809167 0.5630556
7  1978 2.170278 2.747778 0.5775000
8  1979 2.157500 2.587500 0.4300000
9  1980 2.203056 2.574444 0.3713889
10 1981 2.157222 2.446111 0.2888889
11 1982 2.147778 2.492500 0.3447222
12 1983 2.150000 2.378611 0.2286111
13 1984 2.176111 2.491111 0.3150000
14 1985 2.234722 2.568333 0.3336111
15 1986 2.130833 2.415278 0.2844444
16 1987 2.197222 2.422500 0.2252778
17 1988 2.145278 2.408333 0.2630556
18 1989 2.151667 2.409167 0.2575000
19 1990 2.138611 2.423333 0.2847222
20 1991 2.185000 2.405000 0.2200000
21 1992 2.137222 2.395278 0.2580556
22 1993 2.159167 2.424167 0.2650000
23 1994 2.120833 2.362500 0.2416667
24 1995 2.156111 2.419722 0.2636111
25 1996 2.154167 2.453333 0.2991667
26 1997 2.176111 2.439722 0.2636111
27 1998 2.126111 2.389167 0.2630556
28 1999 2.164444 2.390278 0.2258333
29 2000 2.163056 2.436389 0.2733333
30 2001 2.161944 2.398056 0.2361111
31 2002 2.150556 2.345278 0.1947222
32 2003 2.169722 2.422222 0.2525000
33 2004 2.176944 2.407500 0.2305556
34 2005 2.195833 2.420278 0.2244444
35 2006 2.120556 2.393889 0.2733333
36 2007 2.236944 2.488333 0.2513889
37 2008 2.129444 2.423611 0.2941667
38 2009 2.145000 2.537778 0.3927778
39 2010 2.097778 2.436389 0.3386111
40 2011 2.050556 2.376667 0.3261111
41 2012 2.211111 2.530556 0.3194444
42 2013 2.172778 2.440278 0.2675000
43 2014 2.143611 2.333056 0.1894444
44 2015 2.154722 2.415278 0.2605556
45 2016 2.212500 2.488611 0.2761111
46 2017 2.160278 2.364444 0.2041667
47 2018 2.266111 2.665000 0.3988889
48 2019 2.132500 2.391944 0.2594444

Plot the difference between men's and women's race times by year.

In [22]:
options(repr.plot.res = 250, repr.plot.width = 5, repr.plot.height = 4)

In [29]:
p = ggplot(df, aes(x = year, y = difference)) +
    geom_line()

p

ERROR while rich displaying an object: Error in `geom_line()`:
! Problem while computing aesthetics.
ℹ Error occurred in the 1st layer.
Caused by error:
! object 'difference' not found

Traceback:
1. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
2. tryCatchList(expr, classes, parentenv, handlers)
3. tryCatchOne(expr, names, parentenv, handlers[[1L]])
4. doTryCatch(return(expr), name, parentenv, handler)
5. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr))
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr))
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
6. repr::mime2repr[[mime]](obj)
7. repr_text.default(obj)
8. paste(capture.output(print(obj)), collapse = "\n")
9. capture.output(print(obj))
10. withVisible(...elt(i))
11. print(obj)
12. print.ggplot(obj)
13. ggplot_build(x)
14. ggplot_build.ggplot(x)
15. by_layer(function(l, d) l$compute_aesthetics(d, plot), layers,
  .     data, "computing aesthetics")
16. try_fetch(for (i in seq_along(data)) {
  .     out[[i]] <- f(l = layers[[i]], d = data[[i]])
  . }, error = function(cnd) {
  .     cli::cli_abort(c("Problem while {step}.", i = "Error occurred in the {ordinal(i)} layer."),
  .         call = layers[[i]]$constructor, parent = cnd)
  . })
17. tryCatch(withCallingHandlers(expr, condition = function(cnd) {
  .     {
  .         .__handler_frame__. <- TRUE
  .         .__setup_frame__. <- frame
  .         if (inherits(cnd, "message")) {
  .             except <- c("warning", "error")
  .         }
  .         else if (inherits(cnd, "warning")) {
  .             except <- "error"
  .         }
  .         else {
  .             except <- ""
  .         }
  .     }
  .     while (!is_null(cnd)) {
  .         if (inherits(cnd, "error")) {
  .             out <- handlers[[1L]](cnd)
  .             if (!inherits(out, "rlang_zap"))
  .                 throw(out)
  .         }
  .         inherit <- .subset2(.subset2(cnd, "rlang"), "inherit")
  .         if (is_false(inherit)) {
  .             return()
  .         }
  .         cnd <- .subset2(cnd, "parent")
  .     }
  . }), stackOverflowError = handlers[[1L]])
18. tryCatchList(expr, classes, parentenv, handlers)
19. tryCatchOne(expr, names, parentenv, handlers[[1L]])
20. doTryCatch(return(expr), name, parentenv, handler)
21. withCallingHandlers(expr, condition = function(cnd) {
  .     {
  .         .__handler_frame__. <- TRUE
  .         .__setup_frame__. <- frame
  .         if (inherits(cnd, "message")) {
  .             except <- c("warning", "error")
  .         }
  .         else if (inherits(cnd, "warning")) {
  .             except <- "error"
  .         }
  .         else {
  .             except <- ""
  .         }
  .     }
  .     while (!is_null(cnd)) {
  .         if (inherits(cnd, "error")) {
  .             out <- handlers[[1L]](cnd)
  .             if (!inherits(out, "rlang_zap"))
  .                 throw(out)
  .         }
  .         inherit <- .subset2(.subset2(cnd, "rlang"), "inherit")
  .         if (is_false(inherit)) {
  .             return()
  .         }
  .         cnd <- .subset2(cnd, "parent")
  .     }
  . })
22. f(l = layers[[i]], d = data[[i]])
23. l$compute_aesthetics(d, plot)
24. compute_aesthetics(..., self = self)
25. scales_add_defaults(plot$scales, data, aesthetics, plot$plot_env)
26. lapply(aesthetics[new_aesthetics], eval_tidy, data = data)
27. FUN(X[[i]], ...)
28. .handleSimpleError(function (cnd)
  . {
  .     {
  .         .__handler_frame__. <- TRUE
  .         .__setup_frame__. <- frame
  .         if (inherits(cnd, "message")) {
  .             except <- c("warning", "error")
  .         }
  .         else if (inherits(cnd, "warning")) {
  .             except <- "error"
  .         }
  .         else {
  .             except <- ""
  .         }
  .     }
  .     while (!is_null(cnd)) {
  .         if (inherits(cnd, "error")) {
  .             out <- handlers[[1L]](cnd)
  .             if (!inherits(out, "rlang_zap"))
  .                 throw(out)
  .         }
  .         inherit <- .subset2(.subset2(cnd, "rlang"), "inherit")
  .         if (is_false(inherit)) {
  .             return()
  .         }
  .         cnd <- .subset2(cnd, "parent")
  .     }
  . }, "object 'difference' not found", base::quote(NULL))
29. h(simpleError(msg, call))
30. handlers[[1L]](cnd)
31. cli::cli_abort(c("Problem while {step}.", i = "Error occurred in the {ordinal(i)} layer."),
  .     call = layers[[i]]$constructor, parent = cnd)
32. rlang::abort(message, ..., call = call, use_cli_format = TRUE,
  .     .frame = .frame)
33. signal_abort(cnd, .file)